pipeline {
  agent any
  stages{
      stage('SCM CheckOut'){
          git 'https://github.com/SuchansineeNice/demo1.git'
      }
      stage('Package'){
        //Get maven home path
        def mvnHome = tool name: 'maven3_5_0', type: 'maven'
        sh "${mvnHome}/bin/mvn package"
      }
  }
}
