pipeline{
  stages{
    stage('SCM CheckOut'){
      steps{
        git 'https://github.com/SuchansineeNice/demo1.git'
      }
    }
    stage('Compile-Package'){
      steps{
        sh "mvn package"
      }
    }
  }
  
}
